// Code generated by protoc-gen-go. DO NOT EDIT.
// source: integers.proto

package integers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListMinutesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMinutesRequest) Reset()         { *m = ListMinutesRequest{} }
func (m *ListMinutesRequest) String() string { return proto.CompactTextString(m) }
func (*ListMinutesRequest) ProtoMessage()    {}
func (*ListMinutesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{0}
}

func (m *ListMinutesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMinutesRequest.Unmarshal(m, b)
}
func (m *ListMinutesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMinutesRequest.Marshal(b, m, deterministic)
}
func (m *ListMinutesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMinutesRequest.Merge(m, src)
}
func (m *ListMinutesRequest) XXX_Size() int {
	return xxx_messageInfo_ListMinutesRequest.Size(m)
}
func (m *ListMinutesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMinutesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMinutesRequest proto.InternalMessageInfo

type Minute struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OpenDate             string   `protobuf:"bytes,2,opt,name=openDate,proto3" json:"openDate,omitempty"`
	OpenTime             string   `protobuf:"bytes,3,opt,name=openTime,proto3" json:"openTime,omitempty"`
	Open                 float32  `protobuf:"fixed32,4,opt,name=open,proto3" json:"open,omitempty"`
	High                 float32  `protobuf:"fixed32,5,opt,name=high,proto3" json:"high,omitempty"`
	Low                  float32  `protobuf:"fixed32,6,opt,name=low,proto3" json:"low,omitempty"`
	Close                float32  `protobuf:"fixed32,7,opt,name=close,proto3" json:"close,omitempty"`
	Contracts            float32  `protobuf:"fixed32,8,opt,name=contracts,proto3" json:"contracts,omitempty"`
	Trades               float32  `protobuf:"fixed32,9,opt,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Minute) Reset()         { *m = Minute{} }
func (m *Minute) String() string { return proto.CompactTextString(m) }
func (*Minute) ProtoMessage()    {}
func (*Minute) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d2a4376ec32b36, []int{1}
}

func (m *Minute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Minute.Unmarshal(m, b)
}
func (m *Minute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Minute.Marshal(b, m, deterministic)
}
func (m *Minute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Minute.Merge(m, src)
}
func (m *Minute) XXX_Size() int {
	return xxx_messageInfo_Minute.Size(m)
}
func (m *Minute) XXX_DiscardUnknown() {
	xxx_messageInfo_Minute.DiscardUnknown(m)
}

var xxx_messageInfo_Minute proto.InternalMessageInfo

func (m *Minute) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Minute) GetOpenDate() string {
	if m != nil {
		return m.OpenDate
	}
	return ""
}

func (m *Minute) GetOpenTime() string {
	if m != nil {
		return m.OpenTime
	}
	return ""
}

func (m *Minute) GetOpen() float32 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Minute) GetHigh() float32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Minute) GetLow() float32 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Minute) GetClose() float32 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *Minute) GetContracts() float32 {
	if m != nil {
		return m.Contracts
	}
	return 0
}

func (m *Minute) GetTrades() float32 {
	if m != nil {
		return m.Trades
	}
	return 0
}

func init() {
	proto.RegisterType((*ListMinutesRequest)(nil), "integers.ListMinutesRequest")
	proto.RegisterType((*Minute)(nil), "integers.Minute")
}

func init() { proto.RegisterFile("integers.proto", fileDescriptor_e7d2a4376ec32b36) }

var fileDescriptor_e7d2a4376ec32b36 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xdd, 0xfe, 0x89, 0xc9, 0x08, 0x5a, 0x86, 0x22, 0x43, 0xe9, 0xa1, 0xe4, 0xd4, 0x53,
	0x11, 0x7d, 0x02, 0xc1, 0xa3, 0x82, 0x84, 0xbe, 0x40, 0x9a, 0x0e, 0xed, 0x42, 0x9a, 0xad, 0x3b,
	0x53, 0xc5, 0x97, 0xf5, 0x59, 0x64, 0x37, 0x69, 0x23, 0x78, 0x9b, 0xef, 0xfb, 0x2e, 0xbb, 0x3f,
	0xb8, 0xb5, 0x8d, 0xf2, 0x8e, 0xbd, 0xac, 0x8e, 0xde, 0xa9, 0xc3, 0xf4, 0xcc, 0xf9, 0x14, 0xf0,
	0xd5, 0x8a, 0xbe, 0xd9, 0xe6, 0xa4, 0x2c, 0x05, 0x7f, 0x9c, 0x58, 0x34, 0xff, 0x31, 0x90, 0xb4,
	0x0a, 0xef, 0x21, 0x91, 0xef, 0xc3, 0xc6, 0xd5, 0x64, 0x16, 0x66, 0x99, 0x15, 0x1d, 0xe1, 0x0c,
	0x52, 0x77, 0xe4, 0xe6, 0xa5, 0x54, 0xa6, 0x41, 0x2c, 0x17, 0x3e, 0xb7, 0xb5, 0x3d, 0x30, 0x0d,
	0xfb, 0x16, 0x18, 0x11, 0x46, 0xe1, 0xa6, 0xd1, 0xc2, 0x2c, 0x07, 0x45, 0xbc, 0x83, 0xdb, 0xdb,
	0xdd, 0x9e, 0xc6, 0xad, 0x0b, 0x37, 0x4e, 0x60, 0x58, 0xbb, 0x2f, 0x4a, 0xa2, 0x0a, 0x27, 0x4e,
	0x61, 0x5c, 0xd5, 0x4e, 0x98, 0xae, 0xa3, 0x6b, 0x01, 0xe7, 0x90, 0x55, 0xae, 0x51, 0x5f, 0x56,
	0x2a, 0x94, 0xc6, 0xd2, 0x8b, 0xf0, 0x7a, 0xf5, 0xe5, 0x96, 0x85, 0xb2, 0x98, 0x3a, 0x7a, 0x5c,
	0xc3, 0x5d, 0xf7, 0xe5, 0x77, 0xef, 0x3e, 0xed, 0x96, 0x3d, 0x3e, 0xc3, 0xcd, 0x9f, 0x25, 0x70,
	0xbe, 0xba, 0x6c, 0xf6, 0x7f, 0xa0, 0xd9, 0xa4, 0xaf, 0x6d, 0xc9, 0xaf, 0x1e, 0xcc, 0x26, 0x89,
	0xeb, 0x3e, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x90, 0x4e, 0x2b, 0x4a, 0x6f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MinutesProviderClient is the client API for MinutesProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MinutesProviderClient interface {
	ListMinutes(ctx context.Context, in *ListMinutesRequest, opts ...grpc.CallOption) (MinutesProvider_ListMinutesClient, error)
}

type minutesProviderClient struct {
	cc *grpc.ClientConn
}

func NewMinutesProviderClient(cc *grpc.ClientConn) MinutesProviderClient {
	return &minutesProviderClient{cc}
}

func (c *minutesProviderClient) ListMinutes(ctx context.Context, in *ListMinutesRequest, opts ...grpc.CallOption) (MinutesProvider_ListMinutesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MinutesProvider_serviceDesc.Streams[0], "/integers.MinutesProvider/ListMinutes", opts...)
	if err != nil {
		return nil, err
	}
	x := &minutesProviderListMinutesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MinutesProvider_ListMinutesClient interface {
	Recv() (*Minute, error)
	grpc.ClientStream
}

type minutesProviderListMinutesClient struct {
	grpc.ClientStream
}

func (x *minutesProviderListMinutesClient) Recv() (*Minute, error) {
	m := new(Minute)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MinutesProviderServer is the server API for MinutesProvider service.
type MinutesProviderServer interface {
	ListMinutes(*ListMinutesRequest, MinutesProvider_ListMinutesServer) error
}

// UnimplementedMinutesProviderServer can be embedded to have forward compatible implementations.
type UnimplementedMinutesProviderServer struct {
}

func (*UnimplementedMinutesProviderServer) ListMinutes(req *ListMinutesRequest, srv MinutesProvider_ListMinutesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListMinutes not implemented")
}

func RegisterMinutesProviderServer(s *grpc.Server, srv MinutesProviderServer) {
	s.RegisterService(&_MinutesProvider_serviceDesc, srv)
}

func _MinutesProvider_ListMinutes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListMinutesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinutesProviderServer).ListMinutes(m, &minutesProviderListMinutesServer{stream})
}

type MinutesProvider_ListMinutesServer interface {
	Send(*Minute) error
	grpc.ServerStream
}

type minutesProviderListMinutesServer struct {
	grpc.ServerStream
}

func (x *minutesProviderListMinutesServer) Send(m *Minute) error {
	return x.ServerStream.SendMsg(m)
}

var _MinutesProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "integers.MinutesProvider",
	HandlerType: (*MinutesProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListMinutes",
			Handler:       _MinutesProvider_ListMinutes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "integers.proto",
}
